# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=40)),
                ('special', models.CharField(max_length=40)),
                ('one', models.CharField(max_length=40)),
                ('head', models.CharField(max_length=40)),
                ('six', models.CharField(max_length=40)),
                ('duijiang', models.CharField(max_length=40)),
            ],
        ),
    ]
