# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconn', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='AUDCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='CADCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='CHFCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='CNYCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='CurrencyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EURCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='GBPCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='HKDCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='IDRCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='JPYCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='KRWCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='MYRCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='NZDCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='OilPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odate', models.DateField()),
                ('o92', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('o95', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('o98', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('ohigh', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
            ],
            options={
                'ordering': ('-odate',),
            },
        ),
        migrations.CreateModel(
            name='PHPCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='SEKCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='SGDCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='THBCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='USDCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='VNDCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ZARCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('CashBuying', models.FloatField()),
                ('CashSelling', models.FloatField()),
                ('SpotBuying', models.FloatField()),
                ('SpotSelling', models.FloatField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
