# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconn', '0003_audcurrency_cadcurrency_chfcurrency_cnycurrency_currencycode_eurcurrency_gbpcurrency_hkdcurrency_idr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilprice',
            name='o92',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='oilprice',
            name='o95',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='oilprice',
            name='o98',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='oilprice',
            name='ohigh',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
