# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbconn', '0005_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ('-date',)},
        ),
    ]
